Code cleanup (closes #37, closes #40, closes #41)

diff --git a/bash/clean b/bash/clean
--- a/bash/clean
+++ b/bash/clean
@@ -2,13 +2,24 @@
 #Script for emptying * directories! 
 
 BASH_DIR="/Users/jakeireland/bin/scripts/bash/"
-JSON_FILE=FALSE
+
+
+#Clean up
+clean-exit() {
+    if [[ -f ${BASH_DIR}/textcolours.txt ]]
+    then
+        rm /Users/jakeireland/bin/scripts/bash/textcolours.txt
+    fi
+    exit $?
+}
+
 
 # Colours
-jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' ${BASH_DIR}/textcolours.json | sed -e 's/=\([^" >][^ >]*\)/="\1"/g' >> ${BASH_DIR}/textcolours.txt && source ${BASH_DIR}/textcolours.txt && JSON_FILE=TRUE
+jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' ${BASH_DIR}/textcolours.json | sed -e 's/=\([^" >][^ >]*\)/="\1"/g' >> ${BASH_DIR}/textcolours.txt && source ${BASH_DIR}/textcolours.txt
 
+
+# Help
 HELP="${BWHITE}Invalid option.  Use option -h for help.${NORM}"
-
 display_help() {
     echo -e "\033[1;38mUsage: [sudo] empt [option...]${NORM}"
     echo
@@ -19,6 +30,8 @@ display_help() {
     echo -e "${DARKBBLUE}   -h           ${BYELLOW}Shows help (present output).${NORM}"
 }
 
+
+# Options
 while getopts ":tdh" OPTION; do
         case $OPTION in
                 t)
@@ -37,13 +50,13 @@ while getopts ":tdh" OPTION; do
         esac
 done
 
+
+# If no options
 if [[ -z $1 ]]
 then
     rm -drf ~/Library/Mobile\ Documents/com\~apple\~CloudDocs/.Trash/* && rm -drf ~/.Trash* && rm -drf ~/Downloads/*
 fi
 
+
 # Clean up
-if [[ JSON_FILE=TRUE ]]
-then
-    rm /Users/jakeireland/bin/scripts/bash/textcolours.txt
-fi
+clean-exit
diff --git a/bash/dep-mt b/bash/dep-mt
--- a/bash/dep-mt
+++ b/bash/dep-mt
@@ -2,20 +2,20 @@
 # Script for modding time!
 
 BASH_DIR="/Users/jakeireland/bin/scripts/bash/"
-JSON_FILE=FALSE
 
-# Colours
-jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' ${BASH_DIR}/textcolours.json | sed -e 's/=\([^" >][^ >]*\)/="\1"/g' >> ${BASH_DIR}/textcolours.txt && source ${BASH_DIR}/textcolours.txt && JSON_FILE=TRUE
-
-cleanup() {
-    if [[ JSON_FILE=TRUE ]]
+clean-exit() {
+    if [[ -f ${BASH_DIR}/textcolours.txt ]]
     then
         rm /Users/jakeireland/bin/scripts/bash/textcolours.txt
-    fi 
+    fi
+    exit $?
 }
 
+# Colours
+jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' ${BASH_DIR}/textcolours.json | sed -e 's/=\([^" >][^ >]*\)/="\1"/g' >> ${BASH_DIR}/textcolours.txt && source ${BASH_DIR}/textcolours.txt
+
 # changes directory
-cd ~/IntelliJProjects/Electrum || exit $?
+cd ~/IntelliJProjects/Electrum || clean-exit
 
 # define local variables
 BRANCH=$(git rev-parse --abbrev-ref HEAD)
@@ -36,9 +36,11 @@ display_help() {
     echo -e "\033[1;38;5;26m   -b           \033[1;33mStays on current branch.\033[0;38m"
     echo -e "\033[1;38;5;26m   -h           \033[1;33mShows help (present output).\033[0;38m"
     # Clean up
-    cleanup && exit $?
+    clean-exit
 }
 
+
+# Help
 while getopts "h" OPTION; do
     case $OPTION in
         h)
@@ -47,14 +49,17 @@ while getopts "h" OPTION; do
     esac
 done
 
+
+# If dirty
 if [[ ! -z "$CLEANLINESS" ]]
 then
     echo -e "${DIRTY_BRANCH}" && \
     exec bash && \
-    cleanup && exit $?
+    clean-exit
 fi
 
 
+# Options
 while getopts ":ab" OPTION; do
         case $OPTION in
                 a)
@@ -83,11 +88,13 @@ while getopts ":ab" OPTION; do
                         git checkout "${DESIRED_BRANCH}" && \
                         echo -e "${OPT_ERR}"
                     fi
-                    cleanup && exit $?
+                    clean-exit
                     ;;
         esac
 done
 
+
+# Default option (if empty)
 if [[ -z $1 ]]
 then
     if [ "$BRANCH" = "${DESIRED_BRANCH}" ]
@@ -101,4 +108,10 @@ then
     fi
 fi
 
-cleanup && exec bash
+
+#clean up
+if [[ -f ${BASH_DIR}/textcolours.txt ]]
+then
+    rm /Users/jakeireland/bin/scripts/bash/textcolours.txt
+fi
+exec bash
diff --git a/bash/gl b/bash/gl
--- a/bash/gl
+++ b/bash/gl
@@ -5,18 +5,21 @@
 #ensure you run `brew install yarn && yarn global add taskbook`
 
 BASH_DIR="/Users/jakeireland/bin/scripts/bash/"
-JSON_FILE=FALSE
+
+
+# Clean up
+clean-exit() {
+    if [[ -f ${BASH_DIR}/textcolours.txt ]]
+    then
+        rm /Users/jakeireland/bin/scripts/bash/textcolours.txt
+    fi
+    exit $?
+}
+
 
 # Colours
-jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' ${BASH_DIR}/textcolours.json | sed -e 's/=\([^" >][^ >]*\)/="\1"/g' >> ${BASH_DIR}/textcolours.txt && source ${BASH_DIR}/textcolours.txt && JSON_FILE=TRUE
+jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' ${BASH_DIR}/textcolours.json | sed -e 's/=\([^" >][^ >]*\)/="\1"/g' >> ${BASH_DIR}/textcolours.txt && source ${BASH_DIR}/textcolours.txt
 
-# Small Variabels
-LOGNUMBER=$([[ -z "$1" ]] && echo "10")
-COMMIT_NUMBER_TODAY=$(git rev-list --count --since=yesterday --before=today HEAD)
-BRANCH=$(git rev-parse --abbrev-ref HEAD)
-REPO_NAME=$(basename `git rev-parse --show-toplevel`)
-GHLING=$(github-linguist)
-HELP="${BYELLOW}Not a valid option.  Use -h for help.${BNORM}"
 
 # Help
 display_help() {
@@ -59,6 +62,8 @@ while getopts ":csilh" OPTION; do
                     ;;
                 c)
                     # Prints commit count
+                    COMMIT_NUMBER_TODAY=$(git rev-list --count --since=yesterday --before=today HEAD)
+                    BRANCH=$(git rev-parse --abbrev-ref HEAD)
                     echo -e "\033[1;38;5;2mYou have made $COMMIT_NUMBER_TODAY commits to $REPO_NAME/$BRANCH in the past 24 hours.\033[0;38m"
                     ;;
                 i)
@@ -73,10 +78,18 @@ while getopts ":csilh" OPTION; do
                     display_help
                     ;;
                 \?)
+                    HELP="${BYELLOW}Not a valid option.  Use -h for help.${BNORM}"
                     echo -e "${HELP}" && exit $?
                     ;;
         esac
 done
+
+
+#Variables
+COMMIT_NUMBER_TODAY=$(git rev-list --count --since=yesterday --before=today HEAD)
+BRANCH=$(git rev-parse --abbrev-ref HEAD)
+LOGNUMBER=$([[ -z "$1" ]] && echo "10")
+REPO_NAME=$(basename `git rev-parse --show-toplevel`)
 
 
 if [[ -z $1 ]] || [[ $1 =~ ^[-+]?[0-9]+$ ]]  # if first arg is empty or a positive integer
@@ -94,7 +107,4 @@ then # checks to see if my username is one of the usernames, and if so, prints i
 fi
 
 # Clean up
-if [[ JSON_FILE=TRUE ]]
-then
-    rm /Users/jakeireland/bin/scripts/bash/textcolours.txt
-fi
+clean-exit
