Code cleanup with colours and exit codes

diff --git a/bash/dep-mymacros b/bash/dep-mymacros
--- a/bash/dep-mymacros
+++ b/bash/dep-mymacros
@@ -1,24 +1,40 @@
 #! /bin/bash
 
-#Define local variables
-REPLACING_TEX="\033[01;31mReplacing outdated .tex file(s) in git repository.\033[0;38m"
-COMPLETED_TEX="\033[1;38;5;2m.tex transfer complete.\033[0;38m"
-REPLACING_JSON="\033[01;33mReplacing outdated .json file(s) in git repository.\033[0;38m"
-COMPLETED_JSON="\033[1;38;5;2m.json transfer complete.\033[0;38m"
-ALL_GOOD_TEX="\033[1;38;5;2mYour git repository's templates directory's .tex files are up to date with your local templates directory.\033[0;38m"
-ALL_GOOD_JSON="\033[1;38;5;2mYour git repository's templates directory's .json files are up to date with your local templates directory.\033[0;38m"
-
 GIT_LOCATION="/Users/jakeireland/Documents/my_macros/"
-
 LOCAL_DIR="${GIT_LOCATION}../../.config/texstudio/templates/user/"
 GIT_DIR="${GIT_LOCATION}tea_templates/"
+BASH_DIR="/Users/jakeireland/bin/scripts/bash/"
+
+
+#Clean up
+clean-exit() {
+    if [[ -f ${BASH_DIR}/textcolours.txt ]]
+    then
+        rm /Users/jakeireland/bin/scripts/bash/textcolours.txt
+    fi
+    exit $?
+}
+
+
+# Colours
+jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' ${BASH_DIR}/textcolours.json | sed -e 's/=\([^" >][^ >]*\)/="\1"/g' >> ${BASH_DIR}/textcolours.txt && source ${BASH_DIR}/textcolours.txt
+
+
+#Define local variables
+REPLACING_TEX="${BYELLOW}Replacing outdated .tex file(s) in git repository.${NORM}"
+COMPLETED_TEX="${BGREEN}.tex transfer complete.${NORM}"
+REPLACING_JSON="${BYELLOW}Replacing outdated .json file(s) in git repository.${NORM}"
+COMPLETED_JSON="${BGREEN}.json transfer complete.${NORM}"
+ALL_GOOD_TEX="${BGREEN}Your git repository's templates directory's .tex files are up to date with your local templates directory.${NORM}"
+ALL_GOOD_JSON="${BGREEN}Your git repository's templates directory's .json files are up to date with your local templates directory.${NORM}"
+
 
 DIFFT=false
 DIFFJ=false
 
 #Begin script
 
-cd "${GIT_LOCATION}" || exit $?
+cd "${GIT_LOCATION}" || clean-exit
 
 #check tex files
 for t in "${LOCAL_DIR}"/*.tex; do
@@ -49,3 +65,6 @@ if [ "$DIFFJ" = "false" ]
 then
     echo -e "${ALL_GOOD_JSON}"
 fi
+
+
+clean-exit
