finished checking for app dependencies

diff --git a/bash/oina b/bash/oina
--- a/bash/oina
+++ b/bash/oina
@@ -12,24 +12,27 @@ source ${BASH_DIR}/dependencies/source-dependencies.sh
 [[ $KERNEL == "Darwin" ]] && \
     is-app-then-install "${ATOM}"
 # Installing Atom for Linux
-if [[ $(getconf LONG_BIT) == "64" ]]
+if ! command -v atom > /dev/null 2>&1
 then
-    if [[ $OS == "debian"  ]]
+    if [[ $(getconf LONG_BIT) == "64" ]]
     then
-        cd "${HOME}"/Downloads/
-        wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
-        sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list' && \
-        sudo apt-get update && \
-        sudo apt-get install atom || echo -e "${ERROR_OCCURRED}"
-    fi
-    if [[ $OS == "arch" ]]
+        if [[ $OS == "debian"  ]]
+        then
+            cd "${HOME}"/Downloads/
+            wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
+            sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list' && \
+            sudo apt-get update && \
+            sudo apt-get install atom || echo -e "${ERROR_OCCURRED}"
+        fi
+        if [[ $OS == "arch" ]]
+        then
+            aur_install "${ATOM}" 'https://aur.archlinux.org/cgit/aur.git/snapshot/atom-editor-git.tar.gz'
+        fi
+    elif [[ $(getconf LONG_BIT) == "32" ]]
     then
-        aur_install "${ATOM}" 'https://aur.archlinux.org/cgit/aur.git/snapshot/atom-editor-git.tar.gz'
+        echo -e "${BYELLOW}Sorry, you need to manually download Atom on 32-bit systems.${NORM}" && \
+        clean-exit
     fi
-elif [[ $(getconf LONG_BIT) == "32" ]]
-then
-    echo -e "${BYELLOW}Sorry, you need to manually download Atom on 32-bit systems.${NORM}" && \
-    clean-exit
 fi
 
 display_help() {
