updated help

diff --git a/bash/oinb b/bash/oinb
--- a/bash/oinb
+++ b/bash/oinb
@@ -1,8 +1,50 @@
 #! /bin/bash
 # Script for opening in Brackets.app
+
+
+BASH_DIR="/Users/jakeireland/bin/scripts/bash/"
+
+
+# Clean up
+clean-exit() {
+    if [[ -f ${BASH_DIR}/textcolours.txt ]]
+    then
+        rm /Users/jakeireland/bin/scripts/bash/textcolours.txt
+    fi
+    exit $?
+}
+
+
+# Colours
+jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' ${BASH_DIR}/textcolours.json | sed -e 's/=\([^" >][^ >]*\)/="\1"/g' >> ${BASH_DIR}/textcolours.txt && source ${BASH_DIR}/textcolours.txt
+
+
+
+display_help() {
+    echo -e "${BWHITE}Usage: oinb [option... | file name...]${BWHITE}"
+    echo
+    echo -e "${ITBWHITE}The present script will open a specified file in Brackets.app.  If the file is not found in the current directory, it will look for it in \`~/bin/scripts/bash\`.${NORM}"
+    echo
+    echo -e "${BBLUE}\t -h \t${BYELLOW}Shows help (present output).${NORM}"
+    clean-exit
+}
+
+
+while getopts "h" OPTION; do
+    case $OPTION in
+        h)
+            display_help
+            ;; 
+    esac
+done
+
+
 if [[ -f $1 ]] # Checks to see if file exists in current working directory
 then
     open -a "Brackets.app" $1
 else
     open -a "Brackets.app" ~/bin/scripts/bash/$1
 fi
+
+
+clean-exit
